### ISSUE TITLE
Problem with data presentation in service list

### ISSUE THREAD

**Issue by thfsir** [deepflowio/deepflow#5023]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Grafana Dashbaord

### What you expected to happen

In the service list, there are 2 records for an auto service, and the RED indicator data for the 2 records is different.
Through analysis, it was found that these two auto services can be applied in different auto_ Service_ Type. So, is all my business traffic the sum of two auto services or one of them??

### How to reproduce

In the Grafana service list panel, you can reproduce the issue by viewing the RED indicator of deepflow server in the deepflow namespace.

### DeepFlow version

v6.4.3

### DeepFlow agent list

v6.4.3

### Kubernetes CNI

calico

### Operation-System/Kernel version

5.4

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by lzf575** [comment]
`auto_service` is filled according to priority, the priority is as follows
    `service > pod_group > process > pod_node > chost > ip`

When filtering data using the name of the `auto service`, since specifying the `auto service type` is not supported, all possible `auto service` values ​​will be found.
For example, look for data whose `auto service` is 'wed_shop'. If there is a `pod_group` and `service` both named 'web_shop'.
will return  `auto service = 'web_shop', auto service type = service` and `auto service = web_shop. auto service type= pod_group`,
When the results are grouped by `auto service` by default, 2 sets of data will be generated.
Group 1 is `service` traffic, usually Nodeport or pod cluster ip traffic.
Group 2 is the traffic of the `podgroup`, except the service port and IP, other traffic.

If you need to check the traffic of all `pod groups`, use `pod group` filtering, and do not use `auto service grouping` in the results.
