### ISSUE TITLE
[BUG] request to http://deepflow-agent.deepflow/api/v1/otel/trace/v1/traces responded with HTTP Status Code 404

### ISSUE THREAD

**Issue by jiaozi07** [deepflowio/deepflow#7121]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Agent

### What you expected to happen

2024-06-26T09:26:47.019Z error exporterhelper/queue_sender.go:90 Exporting failed. Dropping data. {"kind": "exporter", "data_type": "traces", "name": "otlphttp", "error": "not retryable error: Permanent error: rpc error: code = Unimplemented desc = error exporting items, request to http://deepflow-agent.deepflow/api/v1/otel/trace/v1/traces responded with HTTP Status Code 404", "dropped_items": 1}
go.opentelemetry.io/collector/exporter/exporterhelper.newQueueSender.func1
 go.opentelemetry.io/collector/exporter@v0.103.0/exporterhelper/queue_sender.go:90
go.opentelemetry.io/collector/exporter/internal/queue.(*boundedMemoryQueue[...]).Consume
 go.opentelemetry.io/collector/exporter@v0.103.0/internal/queue/bounded_memory_queue.go:52
go.opentelemetry.io/collector/exporter/internal/queue.(*Consumers[...]).Start.func1
 go.opentelemetry.io/collector/exporter@v0.103.0/internal/queue/consumers.go:43

external_agent_http_proxy_enabled: 1
external_agent_http_proxy_port: 38086

### DeepFlow version

```
kubectl exec -it -n deepflow deploy/deepflow-server -- deepflow-server -v
Name: deepflow-server community edition
Branch: v6.5
CommitID: 72cd65d913407b3c6a41b6d11df24018fb88a09f
RevCount: 10624
Compiler: go version go1.21.11 linux/amd64
CompileTime: 2024-06-26 05:30:34
```
```
kubectl exec -it -n deepflow ds/deepflow-agent -- deepflow-agent -v
Defaulted container "deepflow-agent" out of: deepflow-agent, configure-sysctl (init)
10625-c79a8886bb8a11ad0a1f0f7ba6dbb43f34145c1a
Name: deepflow-agent community edition
Branch: v6.5
CommitId: c79a8886bb8a11ad0a1f0f7ba6dbb43f34145c1a
RevCount: 10625
Compiler: rustc 1.77.1 (7cf61ebde 2024-03-27)

```

### Kubernetes CNI

1.26.3

### Operation-System/Kernel version

```
"CentOS Linux 7 (Core)"
5.4.277-1.el7.elrepo.x86_64
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by yujianweilai** [comment]
i hava same problem while otel-collector send trace to deepflow-agent.

deepflow version info:
[root@staging-cetccx-master1 otel]# kubectl exec -it -n deepflow deploy/deepflow-server -- deepflow-server -v
Name: deepflow-server community edition
Branch: v6.5
CommitID: 8555e64f065b19a98a207ee99dd46880c978ab6e
RevCount: 10792
Compiler: go version go1.21.12 linux/amd64
CompileTime: 2024-08-01 15:36:18

Otel-collector version:
v0.85.0( because my k8s version 1.19.6)

error log:
2024-08-07T02:39:34.950Z        error   exporterhelper/queued_retry.go:319      Exporting failed. The error is not retryable. Dropping data.    {"kind": "exporter", "data_type": "traces", "name": "otlphttp", "error": "Permanent error: error exporting items, request to http://deepflow-agent.deepflow/api/v1/otel/trace/v1/traces responded with HTTP Status Code 404", "dropped_items": 4}
go.opentelemetry.io/collector/exporter/exporterhelper.(*retrySender).send
        go.opentelemetry.io/collector/exporter@v0.85.0/exporterhelper/queued_retry.go:319
go.opentelemetry.io/collector/exporter/exporterhelper.(*tracesExporterWithObservability).send
        go.opentelemetry.io/collector/exporter@v0.85.0/exporterhelper/traces.go:180
go.opentelemetry.io/collector/exporter/exporterhelper.(*queueSender).start.func1
        go.opentelemetry.io/collector/exporter@v0.85.0/exporterhelper/queued_retry.go:126
go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*boundedMemoryQueue).Start.func1
        go.opentelemetry.io/collector/exporter@v0.85.0/exporterhelper/internal/bounded_memory_queue.go:52
2024-08-07T02:39:39.951Z        info    TracesExporter  {"kind": "exporter", "data_type": "traces", "name": "logging", "resource spans": 1, "spans": 5}


how to solve if ?


Thanks

**Comment by yujianweilai** [comment]
试着降低了三个版本，“request to http://deepflow-agent.deepflow/api/v1/otel/trace/v1/traces responded with HTTP Status Code 404”问题还是存在。。。
[root@staging-cetccx-master1 deepflow]# helm install deepflow -n deepflow deepflow/deepflow --create-namespace --version=6.2.606 -f values-custom.yaml ^C
[root@staging-cetccx-master1 deepflow]# helm install deepflow -n deepflow deepflow/deepflow --create-namespace --version=6.3.013 -f values-custom.yaml ^C
[root@staging-cetccx-master1 deepflow]# helm install deepflow -n deepflow deepflow/deepflow --create-namespace --version=6.4.013 -f values-custom.yaml ^C
